### ISSUE TITLE
http-client is required for gRPC managed channel configuration

### ISSUE THREAD

**Issue by olamelin** [micronaut-projects/micronaut-grpc#106]
**Background**
We are using Micronaut to create a service that will call other services via gRPC. 
Given the example from the documentation
```
grpc:
    channels:
        greeter:
            address: '${my.server}:${my.port}'
            plaintext: true
            max-retry-attempts: 10
```
The address of greeter is not resolved correctly

### Steps to Reproduce

1. Setup a simple project using the "micronaut-grpc-runtime"
2. Configure a managed channel like so
```
grpc:
    channels:
        greeter:
            address: 'localhost:8082'
            plaintext: true
            max-retry-attempts: 10
```

3. Create a gRPC stub
```
@Singleton
GreeterGrpc.GreeterStub reactiveStub(
    @GrpcChannel("greeter")
    ManagedChannel channel) {
    return GreeterGrpc.newStub(
            channel
    );
}
```

### Expected Behaviour

The stub will try to connect to localhost:8082 for the greeter service endpoint

### Actual Behaviour

Micronaut will try to service discover the service with name "greeter"

### Workaround / Cause
The cause is that the GrpcManagedChannelConfiguration (https://github.com/micronaut-projects/micronaut-grpc/blob/829128a53dd66b77abc7a193fe66166d54a57f83/grpc-runtime/src/main/java/io/micronaut/grpc/channels/GrpcManagedChannelConfiguration.java#L55 ) can not convert "localhost:8082" to a SocketAddress. 
The type converter for SocketAddress is located in the http-client https://github.com/micronaut-projects/micronaut-core/blob/e9378a1adf1873bbb30889b74a5498c6cab89eca/http-client/src/main/java/io/micronaut/http/client/converters/SocketAddressConverter.java

The workaround is to also add a dependency on http-client module and everything works as it should
