### ISSUE TITLE
GRPC Server certificates and keys are not loaded from filesystem

### ISSUE THREAD

**Issue by arap** [micronaut-projects/micronaut-grpc#165]
I'm trying to run GRPC sever using ssl certificates. According to the docs, I can specify path to certificates like this:
```
grpc:
    server:
        ssl:
            cert-chain: '/path/to/my.cert'
            private-key: '/path/to/my.key'
```
However, my certificates are mounted in file system, and paths above can only be loaded from resources. 
I tried different paths patterns like `/path/to/my.cert`, `file:/path/to/my.cert`, `file://path/to/my.cert`, none of them worked.
Debugging through the code I found a line `final Optional<InputStream> certChain = sslConfiguration.getCertChain() .flatMap(environment::getResourceAsStream);` which suggests that framework use some kind of classpath resource loader to load certs.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Setup app with grpc service
2. set grpc server configuration
```
grpc:
  server:
    port: 8443
    ssl:
      cert-chain: 'file://Users/szymonmysiak/some/path/tls.crt'
      private-key: 'file://Users/szymonmysiak/some/path/tls.key'
```

### Expected Behaviour

There is possibility to load certificates from both filesystem and classpath

### Actual Behaviour

Only classpath files are considered

### Environment Information

- **Operating System**: Macos Catalina 10.15.5
- **Micronaut Version:** core: 2.0.0, grpc: 2.0.0
- **JDK Version:** 11
